- hosts: localhost
  connection: local  #-don't use ssh
  become: true

#  pre_tasks:
#    - name: apt update
#      apt:
#        update_cache: yes
#      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml

