- name: ansible user
  user:
    name: ansible
    system: yes

- name: ansible sudoer
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode:  0440

- name: rob sudoer
  copy:
    src: files/sudoers_rob
    dest: /etc/sudoers.d/rob
    owner: root
    group: root
    mode:  0440

